export * from '../Pages/Home/Home'
export * from '../Pages/Teachers/Teachers'
export * from '../Pages/Header/Header'
//export * from '../pages/pages/HomeCarousel'
//export * from '../pages/pages/Footer'
