export * from '../Pages/Home/Home'
export * from '../Pages/Teachers/Teachers'
export * from '../Pages/Header/Header'
export * from '../Pages/Testimonios/Testimonios'
export * from '../Pages/Faqs/Faqs'
export * from '../Pages/Clases/Clases'
//export * from '../pages/pages/HomeCarousel'
//export * from '../pages/pages/Footer'
